global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: true        # Dashboard accesible en :8080 sin auth (solo lab local)

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: oob-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

# SIN certificatesResolvers — Traefik usará self-signed automáticamente

serversTransport:
  insecureSkipVerify: true
