services:
  orchestrator:
    build: .
    container_name: orchestrator
    restart: unless-stopped
    ports:
      - "127.0.0.1:8020:8000"
    networks:
      - oob-network
      - single-node_default

    env_file:
      - .env

    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_BUCKET: evidence
      MINIO_SECURE: "false"
      PYTHONUNBUFFERED: "1"

      # --- Fase 7: Observabilidad / Métricas ---
      OS_URL: https://single-node-wazuh.indexer-1:9200
      OS_USER: admin
      OS_PASS: ${OS_PASS}
      OS_INDEX: tfm-metrics-events

    volumes:
      - ../fase7-observabilidad/shared:/app/shared:ro

networks:
  oob-network:
    external: true
  single-node_default:
    external: true
