services:
  hbbs:
    image: rustdesk/rustdesk-server:1.1.14
    container_name: rustdesk-hbbs
    command: hbbs -r rustdesk-hbbr:21117 -k _
    restart: unless-stopped
    volumes:
      - ./rustdesk/data:/root
    ports:
      - "${TAILNET_IP}:21115:21115"
      - "${TAILNET_IP}:21116:21116"
      - "${TAILNET_IP}:21116:21116/udp"
      - "${TAILNET_IP}:21118:21118"
    networks:
      - oob-network

  hbbr:
    image: rustdesk/rustdesk-server:1.1.14
    container_name: rustdesk-hbbr
    command: hbbr -k _
    restart: unless-stopped
    volumes:
      - ./rustdesk/data:/root
    ports:
      - "${TAILNET_IP}:21117:21117"
      - "${TAILNET_IP}:21119:21119"
    networks:
      - oob-network

networks:
  oob-network:
    external: true
